name: Test msgpack-zig
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - zig_version: 'master'
            experimental: true
          - zig_version: '0.7.1'
            experimental: false
    continue-on-error: '${{ matrix.experimental }}'
    runs-on: ubuntu-latest
    steps:
      - run: >-
          curl
          `curl https://ziglang.org/download/index.json | jq -r ".\"${{ matrix.zig_version }}\".\"x86_64-linux\".tarball"`
          | tar Jxf - -C /opt
      - run: sudo sh -c "mv /opt/zig-*/zig /usr/local/bin && mv /opt/zig-*/lib/zig /usr/local/lib/zig"
      - uses: actions/checkout@v1
      - run: make build
